/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package cs6253.project;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (1.0.0-dev)", date = "2014-9-25")
public class SpellResponse implements org.apache.thrift.TBase<SpellResponse, SpellResponse._Fields>, java.io.Serializable, Cloneable, Comparable<SpellResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SpellResponse");

  private static final org.apache.thrift.protocol.TField IS_CORRECT_FIELD_DESC = new org.apache.thrift.protocol.TField("is_correct", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new SpellResponseStandardSchemeFactory());
    schemes.put(TupleScheme.class, new SpellResponseTupleSchemeFactory());
  }

  public List<Boolean> is_correct; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    IS_CORRECT((short)1, "is_correct");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // IS_CORRECT
          return IS_CORRECT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.IS_CORRECT, new org.apache.thrift.meta_data.FieldMetaData("is_correct", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SpellResponse.class, metaDataMap);
  }

  public SpellResponse() {
  }

  public SpellResponse(
    List<Boolean> is_correct)
  {
    this();
    this.is_correct = is_correct;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SpellResponse(SpellResponse other) {
    if (other.isSetIs_correct()) {
      List<Boolean> __this__is_correct = new ArrayList<Boolean>(other.is_correct);
      this.is_correct = __this__is_correct;
    }
  }

  public SpellResponse deepCopy() {
    return new SpellResponse(this);
  }

  @Override
  public void clear() {
    this.is_correct = null;
  }

  public int getIs_correctSize() {
    return (this.is_correct == null) ? 0 : this.is_correct.size();
  }

  public java.util.Iterator<Boolean> getIs_correctIterator() {
    return (this.is_correct == null) ? null : this.is_correct.iterator();
  }

  public void addToIs_correct(boolean elem) {
    if (this.is_correct == null) {
      this.is_correct = new ArrayList<Boolean>();
    }
    this.is_correct.add(elem);
  }

  public List<Boolean> getIs_correct() {
    return this.is_correct;
  }

  public SpellResponse setIs_correct(List<Boolean> is_correct) {
    this.is_correct = is_correct;
    return this;
  }

  public void unsetIs_correct() {
    this.is_correct = null;
  }

  /** Returns true if field is_correct is set (has been assigned a value) and false otherwise */
  public boolean isSetIs_correct() {
    return this.is_correct != null;
  }

  public void setIs_correctIsSet(boolean value) {
    if (!value) {
      this.is_correct = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case IS_CORRECT:
      if (value == null) {
        unsetIs_correct();
      } else {
        setIs_correct((List<Boolean>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case IS_CORRECT:
      return getIs_correct();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case IS_CORRECT:
      return isSetIs_correct();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof SpellResponse)
      return this.equals((SpellResponse)that);
    return false;
  }

  public boolean equals(SpellResponse that) {
    if (that == null)
      return false;

    boolean this_present_is_correct = true && this.isSetIs_correct();
    boolean that_present_is_correct = true && that.isSetIs_correct();
    if (this_present_is_correct || that_present_is_correct) {
      if (!(this_present_is_correct && that_present_is_correct))
        return false;
      if (!this.is_correct.equals(that.is_correct))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_is_correct = true && (isSetIs_correct());
    list.add(present_is_correct);
    if (present_is_correct)
      list.add(is_correct);

    return list.hashCode();
  }

  @Override
  public int compareTo(SpellResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetIs_correct()).compareTo(other.isSetIs_correct());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIs_correct()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.is_correct, other.is_correct);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("SpellResponse(");
    boolean first = true;

    sb.append("is_correct:");
    if (this.is_correct == null) {
      sb.append("null");
    } else {
      sb.append(this.is_correct);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SpellResponseStandardSchemeFactory implements SchemeFactory {
    public SpellResponseStandardScheme getScheme() {
      return new SpellResponseStandardScheme();
    }
  }

  private static class SpellResponseStandardScheme extends StandardScheme<SpellResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SpellResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // IS_CORRECT
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                struct.is_correct = new ArrayList<Boolean>(_list8.size);
                boolean _elem9;
                for (int _i10 = 0; _i10 < _list8.size; ++_i10)
                {
                  _elem9 = iprot.readBool();
                  struct.is_correct.add(_elem9);
                }
                iprot.readListEnd();
              }
              struct.setIs_correctIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SpellResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.is_correct != null) {
        oprot.writeFieldBegin(IS_CORRECT_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.BOOL, struct.is_correct.size()));
          for (boolean _iter11 : struct.is_correct)
          {
            oprot.writeBool(_iter11);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SpellResponseTupleSchemeFactory implements SchemeFactory {
    public SpellResponseTupleScheme getScheme() {
      return new SpellResponseTupleScheme();
    }
  }

  private static class SpellResponseTupleScheme extends TupleScheme<SpellResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SpellResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetIs_correct()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetIs_correct()) {
        {
          oprot.writeI32(struct.is_correct.size());
          for (boolean _iter12 : struct.is_correct)
          {
            oprot.writeBool(_iter12);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SpellResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.BOOL, iprot.readI32());
          struct.is_correct = new ArrayList<Boolean>(_list13.size);
          boolean _elem14;
          for (int _i15 = 0; _i15 < _list13.size; ++_i15)
          {
            _elem14 = iprot.readBool();
            struct.is_correct.add(_elem14);
          }
        }
        struct.setIs_correctIsSet(true);
      }
    }
  }

}

