/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package cs6253.project;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (1.0.0-dev)", date = "2014-9-25")
public class SpellRequest implements org.apache.thrift.TBase<SpellRequest, SpellRequest._Fields>, java.io.Serializable, Cloneable, Comparable<SpellRequest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SpellRequest");

  private static final org.apache.thrift.protocol.TField TO_CHECK_FIELD_DESC = new org.apache.thrift.protocol.TField("to_check", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new SpellRequestStandardSchemeFactory());
    schemes.put(TupleScheme.class, new SpellRequestTupleSchemeFactory());
  }

  public List<String> to_check; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TO_CHECK((short)1, "to_check");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TO_CHECK
          return TO_CHECK;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TO_CHECK, new org.apache.thrift.meta_data.FieldMetaData("to_check", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SpellRequest.class, metaDataMap);
  }

  public SpellRequest() {
  }

  public SpellRequest(
    List<String> to_check)
  {
    this();
    this.to_check = to_check;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SpellRequest(SpellRequest other) {
    if (other.isSetTo_check()) {
      List<String> __this__to_check = new ArrayList<String>(other.to_check);
      this.to_check = __this__to_check;
    }
  }

  public SpellRequest deepCopy() {
    return new SpellRequest(this);
  }

  @Override
  public void clear() {
    this.to_check = null;
  }

  public int getTo_checkSize() {
    return (this.to_check == null) ? 0 : this.to_check.size();
  }

  public java.util.Iterator<String> getTo_checkIterator() {
    return (this.to_check == null) ? null : this.to_check.iterator();
  }

  public void addToTo_check(String elem) {
    if (this.to_check == null) {
      this.to_check = new ArrayList<String>();
    }
    this.to_check.add(elem);
  }

  public List<String> getTo_check() {
    return this.to_check;
  }

  public SpellRequest setTo_check(List<String> to_check) {
    this.to_check = to_check;
    return this;
  }

  public void unsetTo_check() {
    this.to_check = null;
  }

  /** Returns true if field to_check is set (has been assigned a value) and false otherwise */
  public boolean isSetTo_check() {
    return this.to_check != null;
  }

  public void setTo_checkIsSet(boolean value) {
    if (!value) {
      this.to_check = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case TO_CHECK:
      if (value == null) {
        unsetTo_check();
      } else {
        setTo_check((List<String>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case TO_CHECK:
      return getTo_check();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case TO_CHECK:
      return isSetTo_check();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof SpellRequest)
      return this.equals((SpellRequest)that);
    return false;
  }

  public boolean equals(SpellRequest that) {
    if (that == null)
      return false;

    boolean this_present_to_check = true && this.isSetTo_check();
    boolean that_present_to_check = true && that.isSetTo_check();
    if (this_present_to_check || that_present_to_check) {
      if (!(this_present_to_check && that_present_to_check))
        return false;
      if (!this.to_check.equals(that.to_check))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_to_check = true && (isSetTo_check());
    list.add(present_to_check);
    if (present_to_check)
      list.add(to_check);

    return list.hashCode();
  }

  @Override
  public int compareTo(SpellRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetTo_check()).compareTo(other.isSetTo_check());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTo_check()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.to_check, other.to_check);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("SpellRequest(");
    boolean first = true;

    sb.append("to_check:");
    if (this.to_check == null) {
      sb.append("null");
    } else {
      sb.append(this.to_check);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SpellRequestStandardSchemeFactory implements SchemeFactory {
    public SpellRequestStandardScheme getScheme() {
      return new SpellRequestStandardScheme();
    }
  }

  private static class SpellRequestStandardScheme extends StandardScheme<SpellRequest> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SpellRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TO_CHECK
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.to_check = new ArrayList<String>(_list0.size);
                String _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = iprot.readString();
                  struct.to_check.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setTo_checkIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SpellRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.to_check != null) {
        oprot.writeFieldBegin(TO_CHECK_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.to_check.size()));
          for (String _iter3 : struct.to_check)
          {
            oprot.writeString(_iter3);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SpellRequestTupleSchemeFactory implements SchemeFactory {
    public SpellRequestTupleScheme getScheme() {
      return new SpellRequestTupleScheme();
    }
  }

  private static class SpellRequestTupleScheme extends TupleScheme<SpellRequest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SpellRequest struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetTo_check()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetTo_check()) {
        {
          oprot.writeI32(struct.to_check.size());
          for (String _iter4 : struct.to_check)
          {
            oprot.writeString(_iter4);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SpellRequest struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.to_check = new ArrayList<String>(_list5.size);
          String _elem6;
          for (int _i7 = 0; _i7 < _list5.size; ++_i7)
          {
            _elem6 = iprot.readString();
            struct.to_check.add(_elem6);
          }
        }
        struct.setTo_checkIsSet(true);
      }
    }
  }

}

